services:
  mongo:
    container_name: mongodb
    image: mongo:4.4.17-focal
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    restart: always
  world-space:
    container_name: world-space
    depends_on:
      - mongo
    image: world-space:latest
    ports:
       - 6000:5000
version: '3'
