version: '3'
services:
  mongo:
    image: mongo:4.4.17-focal
    container_name: mongodb
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    ports:
      - 8081:8081
  world-space:
    image: world-space:1.0
    container_name: world-space
    depends_on:
      - mongo
    ports:
      - 6001:5000
